"""Static outputs: per-paper folders, daily report, leaderboard and index (Markdown + HTML).

The site directory is self-contained and can be published as-is to GitHub Pages.
"""

from __future__ import annotations

import json
from html import escape
from pathlib import Path

STATUS_LABEL = {
    "reproduced": "Reproduced",
    "partial": "Partially reproduced",
    "not_reproduced": "Not reproduced",
    "unverified": "Ran, no comparable claims",
    "failed": "Failed to run",
}
CSS = """
:root{--bg:#fbfbf8;--fg:#1d1d1b;--muted:#6b6b66;--line:#e2e1dc;--card:#fff;--accent:#2f5d8a;
--ok:#1f7a4d;--warn:#9a6700;--bad:#b42318;--na:#6b6b66}
@media (prefers-color-scheme:dark){:root{--bg:#161615;--fg:#ecebe6;--muted:#9d9c95;--line:#33332f;
--card:#1e1e1c;--accent:#8db7e0;--ok:#5cc28f;--warn:#e0b24f;--bad:#f07c72;--na:#9d9c95}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);
font:15px/1.55 ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}
main{max-width:1080px;margin:0 auto;padding:28px 16px 64px}
h1{font-size:26px;margin:0 0 4px}h2{font-size:18px;margin:32px 0 10px}
a{color:var(--accent)}.muted{color:var(--muted)}nav{margin-bottom:20px;font-size:14px}
nav a{margin-right:14px}.scroll{overflow-x:auto}
table{border-collapse:collapse;width:100%;font-size:14px;background:var(--card)}
th,td{border-bottom:1px solid var(--line);padding:8px 10px;text-align:left;vertical-align:top}
th{font-weight:600;color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.04em}
td.num{font-variant-numeric:tabular-nums;text-align:right;white-space:nowrap}
.badge{display:inline-block;padding:1px 8px;border-radius:999px;font-size:12px;font-weight:600;
border:1px solid currentColor;white-space:nowrap}
.s-reproduced,.v-match{color:var(--ok)}.s-partial{color:var(--warn)}
.s-not_reproduced,.s-failed,.v-mismatch{color:var(--bad)}.s-unverified,.v-missing{color:var(--na)}
.ev{font-size:12px;color:var(--muted)}code,pre{font:12.5px ui-monospace,Menlo,monospace}
pre{background:var(--card);border:1px solid var(--line);padding:10px;overflow-x:auto}
.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}
.card{background:var(--card);border:1px solid var(--line);padding:12px}
.card b{display:block;font-size:22px}
"""


def _page(title: str, body: str, depth: int = 0) -> str:
    up = "../" * depth
    return (f"<!doctype html><html lang=en><head><meta charset=utf-8>"
            f"<meta name=viewport content='width=device-width,initial-scale=1'>"
            f"<link rel=icon href='data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 16 16%22>"
            f"<rect width=%2216%22 height=%2216%22 rx=%223%22 fill=%22%232f5d8a%22/></svg>'>"
            f"<title>{escape(title)}</title><style>{CSS}</style></head><body><main>"
            f"<nav><a href='{up}index.html'>paper-forge</a><a href='{up}leaderboard.html'>Leaderboard</a></nav>"
            f"{body}</main></body></html>")


def _badge(status: str) -> str:
    return f"<span class='badge s-{status}'>{escape(STATUS_LABEL.get(status, status))}</span>"


def _backend(b: str) -> str:
    return "scripted (hand-written reference)" if b == "scripted" else f"{b} (generated)"


def _fmt(v) -> str:
    if isinstance(v, float):
        return f"{v:.4g}"
    return "—" if v is None else str(v)


def _citation(p: dict) -> str:
    authors = ", ".join(p.get("authors", [])[:6]) + (" et al." if len(p.get("authors", [])) > 6 else "")
    year = (p.get("published") or "")[:4]
    return f"{authors} ({year}). {p['title']}. arXiv:{p['arxiv_id']}. https://arxiv.org/abs/{p['arxiv_id']}"


# ---------------------------------------------------------------- per-paper folder

def write_paper_folder(out_dir: Path, paper: dict, results: dict) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "results.json").write_text(json.dumps(results, indent=2, default=str))
    url = f"https://arxiv.org/abs/{paper['arxiv_id']}"
    status = results["status"]
    rows = "\n".join(
        f"| `{c['name']}` | {c['kind']} | {_fmt(c['claimed'])} | {_fmt(c['reproduced'])} | "
        f"{_fmt(c['tolerance'])} | **{c['verdict']}** | {c['source']} |" for c in results["comparisons"])
    label = ("hand-written reference implementation (scripted backend)" if results["backend"] == "scripted"
             else "implementation generated by Claude, run in the sandbox")
    md = f"""# {paper['title']}

**Paper:** [{url}]({url})
**Cite:** {_citation(paper)}

**Status: {STATUS_LABEL.get(status, status)}** — {label}.
Tests passed: {_fmt(results['tests_passed'])} · sandbox: {results['sandbox']} · runtime: {_fmt(results['runtime_s'])} s · attempts: {results['attempts']}
{f"**Error:** `{results['error']}`" if results.get('error') else ''}

## Claimed vs reproduced

| metric | kind | claimed | reproduced | tolerance | verdict | source in paper |
|---|---|---|---|---|---|---|
{rows or '| — | | | | | no comparable claims | |'}

## Fidelity notes (deviations from the paper)

{chr(10).join(results.get('fidelity_notes') or ['- none recorded'])}

## Notes

{chr(10).join('- ' + n for n in results.get('notes', []))}
- The status above is computed by paper-forge from `implementation/metrics.json` written by the
  sandboxed run; see `implementation/run.log` for the full output.
- The paper remains the authority. This implementation was written from the paper's description;
  no code from the authors was copied. Check the paper's license on arXiv before reusing its text or figures.

## Files

- `implementation/` — code, tests (`test_*.py`) and `experiment.py`
- `results.json` — machine-readable results
"""
    (out_dir / "README.md").write_text(md)

    comp = "".join(
        f"<tr><td><code>{escape(c['name'])}</code></td><td>{c['kind']}</td><td class=num>{escape(_fmt(c['claimed']))}</td>"
        f"<td class=num>{escape(_fmt(c['reproduced']))}</td><td class=num>{escape(_fmt(c['tolerance']))}</td>"
        f"<td class='v-{c['verdict']}'><b>{c['verdict']}</b></td><td class=ev>{escape(c['source'])}</td></tr>"
        for c in results["comparisons"]) or "<tr><td colspan=7 class=muted>no comparable claims</td></tr>"
    notes = "".join(f"<li>{escape(n.lstrip('- '))}</li>" for n in results.get("fidelity_notes") or [])
    body = (f"<h1>{escape(paper['title'])}</h1><p class=muted>{escape(_citation(paper))}</p>"
            f"<p><a href='{url}'>{url}</a></p><p>{_badge(status)} <span class=muted>{escape(label)} · tests passed: "
            f"{_fmt(results['tests_passed'])} · sandbox: {escape(results['sandbox'])} · runtime "
            f"{_fmt(results['runtime_s'])} s · attempts {results['attempts']}</span></p>"
            + (f"<p><b>Error:</b> <code>{escape(results['error'])}</code></p>" if results.get("error") else "")
            + "<h2>Claimed vs reproduced</h2><div class=scroll><table><tr><th>metric</th><th>kind</th><th>claimed</th>"
            "<th>reproduced</th><th>tol.</th><th>verdict</th><th>source in paper</th></tr>" + comp + "</table></div>"
            f"<h2>Fidelity notes</h2><ul>{notes or '<li>none recorded</li>'}</ul>"
            "<h2>Files</h2><ul><li><a href='README.md'>README.md</a></li><li><a href='results.json'>results.json</a></li>"
            "<li><a href='implementation/run.log'>implementation/run.log</a></li></ul>"
            + "".join(f"<p class=ev>{escape(n)}</p>" for n in results.get("notes", [])))
    (out_dir / "index.html").write_text(_page(paper["title"], body, depth=2))


# ---------------------------------------------------------------- daily report

def _screen_rows_md(rows: list[dict]) -> str:
    out = ["| score | paper | compute | data | clarity | code | interest | analysis | laptop-feasible |",
           "|---:|---|---:|---:|---:|---:|---:|---|---|"]
    for r in rows:
        c = r["rubric"]["criteria"]
        a = r["analysis"] or {}
        out.append(f"| {r['score']:.1f} | [{r['title']}](https://arxiv.org/abs/{r['arxiv_id']}) `{r['arxiv_id']}` | "
                   + " | ".join(f"{c[k]['score']:.2f}" for k in ("compute", "data", "clarity", "code", "interest"))
                   + f" | {a.get('source', '—')} | {_fmt(a.get('laptop_feasible'))} |")
    return "\n".join(out)


def write_daily(site: Path, day: str, screened: list[dict], runs: list[dict]) -> Path:
    d = site / "daily"
    d.mkdir(parents=True, exist_ok=True)
    top = [r for r in screened if r["analysis"]]
    md = [f"# paper-forge daily report — {day}", "",
          f"{len(screened)} new papers screened; {len(top)} analyzed in depth; {len(runs)} reproduction runs.", "",
          "## Reproductions", ""]
    for run in runs:
        res = run["results"]
        md.append(f"- **{STATUS_LABEL.get(run['status'], run['status'])}** — [{res['paper']['title']}]"
                  f"({res['paper']['url']}) ({_backend(run['backend'])}) → [details](../papers/{run['arxiv_id']}/README.md)")
    if not runs:
        md.append("- none today (reimplementation is opt-in: `forge daily --reimplement`)")
    md += ["", "## Top candidates", ""]
    for r in top:
        a = r["analysis"]
        md += [f"### [{r['title']}](https://arxiv.org/abs/{r['arxiv_id']})",
               f"`{r['arxiv_id']}` · score {r['score']:.1f} · analysis: {a['source']} · "
               f"feasibility {a['feasibility_score']}/10", "", a["method_summary"], ""]
        if a["claimed_metrics"]:
            md.append("Claimed: " + "; ".join(f"{m['name']} {m['value']}{m['unit']} ({m['context']})"
                                             for m in a["claimed_metrics"]))
        md.append("Rubric evidence: " + "; ".join(e for c in r["rubric"]["criteria"].values() for e in c["evidence"]))
        md.append("")
    md += ["## All screened papers", "", _screen_rows_md(screened), "",
           "Scores: weighted mean of rubric criteria (0–1 each) × 100; see README for the rubric."]
    (d / f"{day}.md").write_text("\n".join(md))

    runs_html = "".join(
        f"<tr><td>{_badge(r['status'])}</td><td><a href='../papers/{r['arxiv_id']}/index.html'>"
        f"{escape(r['results']['paper']['title'])}</a> <span class=muted>{r['arxiv_id']}</span></td>"
        f"<td>{_backend(r['backend'])}</td><td class=num>{sum(c['verdict'] == 'match' for c in r['results']['comparisons'])}"
        f"/{len(r['results']['comparisons'])}</td></tr>" for r in runs) or \
        "<tr><td colspan=4 class=muted>No reproduction runs today (opt-in).</td></tr>"
    cards = []
    for r in top:
        a = r["analysis"]
        ev = "; ".join(e for c in r["rubric"]["criteria"].values() for e in c["evidence"])
        claimed = "; ".join(f"{m['name']} {m['value']}{m['unit']}" for m in a["claimed_metrics"]) or "none extracted"
        cards.append(f"<tr><td class=num>{r['score']:.1f}</td><td><a href='https://arxiv.org/abs/{r['arxiv_id']}'>"
                     f"{escape(r['title'])}</a><div class=ev>{escape(a['method_summary'][:400])}</div>"
                     f"<div class=ev>Claimed: {escape(claimed)}</div><div class=ev>Evidence: {escape(ev)}</div></td>"
                     f"<td>{a['feasibility_score']}/10<div class=ev>{escape(a['source'])}</div></td></tr>")
    rows = "".join(
        f"<tr><td class=num>{r['score']:.1f}</td><td><a href='https://arxiv.org/abs/{r['arxiv_id']}'>{escape(r['title'])}</a>"
        f" <span class=muted>{r['arxiv_id']}</span></td>"
        + "".join(f"<td class=num>{r['rubric']['criteria'][k]['score']:.2f}</td>"
                  for k in ("compute", "data", "clarity", "code", "interest")) + "</tr>" for r in screened)
    body = (f"<h1>Daily report — {day}</h1><p class=muted>{len(screened)} new papers screened · {len(top)} analyzed · "
            f"{len(runs)} reproduction runs · <a href='{day}.md'>markdown</a></p>"
            f"<h2>Reproductions</h2><div class=scroll><table><tr><th>status</th><th>paper</th><th>backend</th>"
            f"<th>claims matched</th></tr>{runs_html}</table></div>"
            f"<h2>Top candidates</h2><div class=scroll><table><tr><th>score</th><th>paper</th><th>feasibility</th></tr>"
            f"{''.join(cards) or '<tr><td colspan=3 class=muted>none</td></tr>'}</table></div>"
            f"<h2>All screened papers</h2><div class=scroll><table><tr><th>score</th><th>paper</th><th>compute</th>"
            f"<th>data</th><th>clarity</th><th>code</th><th>interest</th></tr>{rows}</table></div>")
    path = d / f"{day}.html"
    path.write_text(_page(f"paper-forge {day}", body, depth=1))
    return path


# ---------------------------------------------------------------- leaderboard + index

def write_leaderboard(site: Path, runs: list[dict]) -> None:
    order = {s: i for i, s in enumerate(STATUS_LABEL)}
    runs = sorted(runs, key=lambda r: (order.get(r["status"], 9), r["arxiv_id"]))
    md = ["# Reproduction leaderboard", "", "| status | paper | backend | claims matched | tests | last run |",
          "|---|---|---|---:|---|---|"]
    for r in runs:
        res = r["results"]
        m = sum(c["verdict"] == "match" for c in res["comparisons"])
        md.append(f"| {STATUS_LABEL.get(r['status'], r['status'])} | [{res['paper']['title']}]({res['paper']['url']}) "
                  f"| {_backend(r['backend'])} | {m}/{len(res['comparisons'])} | {_fmt(res['tests_passed'])} | {r['day']} |")
    site.mkdir(parents=True, exist_ok=True)
    (site / "leaderboard.md").write_text("\n".join(md))
    rows = "".join(
        f"<tr><td>{_badge(r['status'])}</td><td><a href='papers/{r['arxiv_id']}/index.html'>"
        f"{escape(r['results']['paper']['title'])}</a> <span class=muted>arXiv:{r['arxiv_id']}</span></td>"
        f"<td>{_backend(r['backend'])}</td><td class=num>{sum(c['verdict'] == 'match' for c in r['results']['comparisons'])}"
        f"/{len(r['results']['comparisons'])}</td><td>{_fmt(r['results']['tests_passed'])}</td><td>{r['day']}</td></tr>"
        for r in runs) or "<tr><td colspan=6 class=muted>no runs yet</td></tr>"
    body = ("<h1>Reproduction leaderboard</h1><p class=muted>Latest run per paper and backend. Status is computed from "
            "metrics the sandboxed experiment actually wrote.</p><div class=scroll><table><tr><th>status</th><th>paper</th>"
            f"<th>backend</th><th>claims</th><th>tests</th><th>last run</th></tr>{rows}</table></div>")
    (site / "leaderboard.html").write_text(_page("paper-forge leaderboard", body))


def write_index(site: Path, days: list[str], runs: list[dict]) -> None:
    counts = {s: sum(r["status"] == s for r in runs) for s in STATUS_LABEL}
    cards = "".join(f"<div class=card><b class='s-{s}'>{n}</b>{STATUS_LABEL[s]}</div>" for s, n in counts.items())
    links = "".join(f"<li><a href='daily/{d}.html'>{d}</a></li>" for d in days) or "<li class=muted>no reports yet</li>"
    body = ("<h1>paper-forge</h1><p class=muted>Daily screen of new arXiv papers for laptop-scale reproducibility, "
            "with sandboxed reference implementations and honest claimed-vs-reproduced reports.</p>"
            f"<div class=cards>{cards}</div><h2>Daily reports</h2><ul>{links}</ul>"
            "<p><a href='leaderboard.html'>Reproduction leaderboard →</a></p>")
    (site / "index.html").write_text(_page("paper-forge", body))
